@CleanTeeth.API_HostAddress = http://localhost:5030/api/dentists


GET {{CleanTeeth.API_HostAddress}}?page=1&recordsPerPage=10
ACCEPT: application/json

###

GET {{CleanTeeth.API_HostAddress}}/01990b0f-4bab-759a-acf2-4cedbb892923
ACCEPT: application/json

###

POST {{CleanTeeth.API_HostAddress}}
Content-Type: application/json

{
  "name": "Robert Simmons",
  "email": "simmons@example.com"
}

###

PUT {{CleanTeeth.API_HostAddress}}/01990b0f-4bab-759a-acf2-4cedbb892923
Content-Type: application/json

{
  "name": "Dentist A - Updated",
  "email": "dentistA2@example.com"
}

###

DELETE {{CleanTeeth.API_HostAddress}}/01990b10-5476-7364-a1f0-e4da40e2fa2d