@CleanTeeth.API_HostAddress = https://localhost:7037/api/dentaloffices


GET {{CleanTeeth.API_HostAddress}}
ACCEPT: application/json
Authorization: Bearer CfDJ8LUidAgiWilIkXqxv7v0BzCpDvQW-lgqvoOLxWDn7GJEo_E1oi7qGFzYYTgYCJrM4d_0gKfhrNEQSIjJM5ZKHgNbf7xqVwrJC9fkKlubZt12EeEjQlAAy3pmH9igtDAtJ43LRKCqfHrZUrf-ezTJgqDeb1YSFBvyHRqKF6jvSt_yKXsDS_ftVVkBotrh_ZYDngmpraWedE1CM5h5L98ieZ_kUSh6YtUobHFhRyHIlreAxnOfCGcWJIHGpC3NxgXvN4JJoCysloc8AmBzbBUYosmZuHqt0R3eWMurYwZJnb-Jhli6eP5tCkN2_uBRuTHBGK_0OuzXe7tHWvmukijvd85vgbdd8ubP7o41ifcOMqTZWU3VdxKfoxZ2JpxjPxc8Nofd7Yb_nk-CGdNOBSJ6sr0sX2V2KNYBsXtDwgKChfzCK8YclobSuoRVhFj3Gh6v2dMdQr9uEv0v_OCUNj3E_Re1etxxVMs2k0il9eE6TmSoHrliJwjMSdNLg5Xj4GW4ruGr0qPNMgaKj2ym4rLd69MDgUTErto50_OXQUysKEgcrMM7_jK8wM5OISmQfXHwqbtYgwz3MUpsb_uv83hBUzWpuKVmO44XnTdcj-CH9f67GdVTFC42ZPyyK6_lB4JxlIKNJ7HZnDufdfyfRVRqmRI3PeDYNIJn7JZsDgSjtqqVYmHZey8SaARFjO-Dp9RMDaG69abiQnGwSgMMp4OuIMbTvT9RJqcmpjsyTw059ZTX

###

GET {{CleanTeeth.API_HostAddress}}/0198CD02-22B2-726B-96E5-01E2403CF109
ACCEPT: application/json

###

POST {{CleanTeeth.API_HostAddress}}
Content-Type: application/json

{
  "name": "Dental Office C"
}

###

PUT {{CleanTeeth.API_HostAddress}}/0198cd02-22b2-726b-96e5-01e2403cf109
Content-Type: application/json

{
  "name": "Dental Office A - Updated"
}

###

DELETE {{CleanTeeth.API_HostAddress}}/019906af-5035-794f-8141-ff01423edb2e